version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DB_USER=luuna
      - DB_PASS=luuna
      - DB_NAME=luuna
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: luuna
      MONGO_INITDB_ROOT_PASSWORD: luuna
      MONGO_INITDB_DATABASE: luuna
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: luuna
      ME_CONFIG_MONGODB_ADMINPASSWORD: luuna